[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "retico-huggingfacelm"
dynamic = ["version"]
dependencies = [
    "retico-core @ git+https://github.com/retico-team/retico-core@39e9957ee008b3e13ab4248040929f29056fb4ad",  #pip version out of date
    "transformers",
    "torch",
    "torchvision",
]
authors = [
    {name = "Anna Manaseryan"},
]
description = "A Retico module for HuggingFace text generation models."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["real-time", "HuggingFace", "text-generation", "LM"]

